#!/bin/bash
sudo aptitude install libcurl4-openssl-dev imagemagick build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion libmysqlclient-dev libsqlite3-dev sqlite mysql-server nodejs unzip python-software-properties openjdk-7-jre -y
curl -L https://get.rvm.io | bash -s stable
rvm pkg install zlib
rvm install 1.9.3
